#!/bin/bash

PREFILE=/etc/snapper/.snap-pac-pre
if [ -f $PREFILE ]; then
    SNAPPERPACPRE=$(cat $PREFILE)
    snapper --config root create --cleanup-algorithm number --type post --pre-number $SNAPPERPACPRE --description "$(xargs -0 printf '%s ' < /proc/$PPID/cmdline)"
    rm $PREFILE
else
    echo "WARNING: $PREFILE does not exist, so not performing post snapshot. If you are initially installing snap-pac, this is normal."
fi
