#!/bin/bash

# snap-pac
# https://github.com/wesbarnett/snap-pac
# Copyright (C) 2016 James W. Barnett

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Main script.

set -e

if [[ "$1" != "pre" ]] && [[ "$1" != "post" ]]; then
    echo "ERROR: First argument should either be 'pre' or 'post'."
    exit
fi

declare -r pre_or_post=$1
declare -r prefile_prefix="/usr/share/libalpm/hooks.bin/snap-pac/.pre"
declare -r pacman_cmd="$(echo $(ps -C pacman -o args=) | sed 'sX/usr/bin/pacmanXpacmanXg')"
declare -r snapper_config_dir="/etc/snapper/configs"
declare -r configurations="$(ls $snapper_config_dir)"

for x in $configurations; do

    source $snapper_config_dir/$x
    if [[ $x == "root" ]]; then
        take_snapshot=${PACMAN_PRE_POST:-"yes"}
    else
        take_snapshot=${PACMAN_PRE_POST:-"no"}
    fi
    cleanupalgo=${PACMAN_CLEANUP_ALGORITHM:-"number"}
    pre_description=${PACMAN_PRE_DESCRIPTION:-"$pacman_cmd"}
    post_description=${PACMAN_POST_DESCRIPTION:-"$pacman_cmd"}

    if [[ $take_snapshot == "yes" ]]; then

        if [[ "$pre_or_post" == "pre" ]]; then

            snapper --config $x create --type pre --cleanup-algorithm $cleanupalgo --print-number --description "$post_description" > $prefile_prefix"_"$x

        elif [[ "$pre_or_post" == "post" ]]; then

            if [ -f $prefile_prefix"_"$x ]; then
                snapper --config $x create --cleanup-algorithm $cleanupalgo --type post --pre-number $(cat $prefile_prefix"_"$x) --description "$pre_description"
                rm $prefile_prefix"_"$x
            else
                echo "WARNING: $prefile_prefix"_"$x does not exist, so no post snapshot will be taken. If you are initially installing snap-pac, this is normal."
            fi

        fi

    fi

done
