#!/bin/bash

# snap-pac
# https://github.com/wesbarnett/snap-pac
# Copyright (C) 2016 James W. Barnett

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Takes a snapper post snapshot after a pacman transaction

source /etc/snap-pac.conf

for x in $CONFIGS; do
    if [ -f $PREFILE_PREFIX"_"$x ]; then
        SNAPPERPACPRE=$(cat $PREFILE_PREFIX"_"$x)
        snapper --config $x create --cleanup-algorithm number --type post --pre-number $SNAPPERPACPRE --description "$PRE_DESCRIPTION"
        rm $PREFILE_PREFIX"_"$x
    else
        echo "WARNING: $PREFILE_PREFIX"_"$x does not exist, so not performing post snapshot. If you are initially installing snap-pac, this is normal."
    fi
done
