#!/bin/bash

# snap-pac
# https://github.com/wesbarnett/snap-pac
# Copyright (C) 2016 James W. Barnett

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Main script. Is sourced in hooks and functions are called.
# e.g.: bash -c ". snap-pac; pre"

declare -r prefile_prefix="/usr/share/libalpm/hooks.bin/snap-pac/.pre"

function read_configs
{
    declare -r pacman_cmd="$(echo $(ps -C pacman -o args=) | sed 'sX/usr/bin/pacmanXpacmanXg')"
    declare -i i=0
    for x in $(ls /etc/snapper/configs); do
        source /etc/snapper/configs/$x
        if [[ $x == "root" ]]; then
            take_snapshot[i]=${PACMAN_PRE_POST:-"yes"}
        else
            take_snapshot[i]=${PACMAN_PRE_POST:-"no"}
        fi
        cleanupalgo[i]=${PACMAN_CLEANUP_ALGORITHM:-"number"}
        pre_description[i]=${PACMAN_PRE_DESCRIPTION:-"$pacman_cmd"}
        post_description[i]=${PACMAN_POST_DESCRIPTION:-"$pacman_cmd"}
        i=$(($i+1))
    done
}

function pre
{
    read_configs
    declare -i i=0
    for x in $(ls /etc/snapper/configs); do
        if [[ ${take_snapshot[i]} == "yes" ]];then
            snapper --config $x create --type pre --cleanup-algorithm ${cleanupalgo[i]} --print-number --description "${pre_description[i]}" > $prefile_prefix"_"$x
        fi
        i=$(($i+1))
    done
}

function post 
{
    read_configs
    declare -i i=0
    for x in $(ls /etc/snapper/configs); do
        if [[ ${take_snapshot[i]} == "yes" ]];then
            if [ -f $prefile_prefix"_"$x ]; then
                snapper --config $x create --cleanup-algorithm ${cleanupalgo[i]} --type post --pre-number $(cat $prefile_prefix"_"$x) --description "${post_description[i]}"
                rm $prefile_prefix"_"$x
            else
                echo "WARNING: $prefile_prefix"_"$x does not exist, so no post snapshot for $x configuration will be taken. If you are initially installing snap-pac, this is normal."
            fi
        fi
        i=$(($i+1))
    done
}

function clean
{
    rm /usr/share/libalpm/hooks.bin/snap-pac/.pre*
    echo "NOTE: No post snapshot will be performed for this transaction, since you are removing the pacman hooks."
}
