#!/bin/bash

# snap-pac
# https://github.com/wesbarnett/snap-pac
# Copyright (C) 2016 James W. Barnett

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Takes a snapper post snapshot after a pacman transaction

# Change this variable to include other configs in the post snapshot
# You must also change it in the pre snapshot script
CONFIGS="root"
#CONFIGS="root home"

PACMAN_CMD=$(ps -C pacman -o args=)
PREFILE=/usr/share/libalpm/hooks.bin/snap-pac/.pre
for x in $CONFIGS; do
    if [ -f $PREFILE"_"$x ]; then
        SNAPPERPACPRE=$(cat $PREFILE"_"$x)
        snapper --config $x create --cleanup-algorithm number --type post --pre-number $SNAPPERPACPRE --description "$PACMAN_CMD"
        rm $PREFILE"_"$x
    else
        echo "WARNING: $PREFILE"_"$x does not exist, so not performing post snapshot. If you are initially installing snap-pac, this is normal."
    fi
done
