#!/bin/bash

if [ -f /.snapperpacpre ]; then
    SNAPPERPACPRE=$(cat /.snapperpacpre)
    snapper --config root create --type post --pre-number $SNAPPERPACPRE --description "pacman posttransaction"
    rm /.snapperpacpre
else
    echo "No pacman pre snapshot was performed, so not performing post snapshot. If you are installing pac-snap, this is normal."
fi
