#!/bin/bash

# snap-pac
# https://github.com/wesbarnett/snap-pac
# Copyright (C) 2016 James W. Barnett

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Main script.

set -e

SNAPPER_CONFIG_FILE=/etc/conf.d/snapper

ERRORMSG="\033[00;31mERROR:\033[00m"
WARNINGMSG="\033[00;33mWARNING:\033[00m"

if [[ $EUID -ne 0 ]]; then
    echo -e "$ERRORMSG Script must be run as root." 
    exit 1
fi

if [[ -f "$SNAPPER_CONFIG_FILE" ]]; then
    source "$SNAPPER_CONFIG_FILE"
else
    exit 1
fi

for CONFIG in $SNAPPER_CONFIGS; do

    prefile="/tmp/snap-pac-pre_$CONFIG"
    if [[ -f "$prefile" ]]; then
        rm "$prefile"
    fi

done

exit 0
