name: Run Python Tests
on:
  push:
    branches:
      - python
  pull_request:
    branches:
      - python

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: python -m pip install --upgrade pip pytest
      - name: Run tests with pytest
        run: pytest tests.py
